//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sportsBiddingApp2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bet
    {
        public int Id { get; set; }
        public int MatchId { get; set; }
        public string HomeAway { get; set; }
        public decimal BetAmount { get; set; }
        public Nullable<decimal> Winnings { get; set; }
        public int UserId { get; set; }
    }
}
