//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sportsBiddingApp2._0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sportsDBEntities : DbContext
    {
        public sportsDBEntities()
            : base("name=sportsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sports_Table> Sports_Tables { get; set; }
        public virtual DbSet<User_Admin_Table> User_Admin_Tables { get; set; }
        public virtual DbSet<Bet> Bets { get; set; }
    }
}
