//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sportsBiddingApp2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sports_Table
    {
        public int Bid_ID { get; set; }
        public string Home { get; set; }
        public string Away { get; set; }
        public Nullable<decimal> Bid_Home { get; set; }
        public Nullable<decimal> Bid_Away { get; set; }
        public decimal H__win { get; set; }
        public decimal A__win { get; set; }
        public Nullable<byte> Home_Winner { get; set; }
        public Nullable<byte> Away_Winner { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Match_ID { get; set; }
    }
}
